# Basics of Numpy

In [2]:
import numpy as np

In [3]:
x=np.array([1,2,3,45,5])

In [4]:
print(x)

[ 1  2  3 45  5]


In [5]:
x=np.arange(1,10).reshape(3,3)

In [6]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
x=np.append(x,7)
print(x)

[1 2 3 4 5 6 7 8 9 7]


In [8]:
x=np.array([1,2,3])
y=np.array([1,2,3])
z=x*y
print(z)

[1 4 9]


In [13]:
#defining an array using numpy
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [14]:
#Get shape
a.shape
#Here in the output you'll get (6,) where 6 is the size of the array after comma you'll not find any value which represents it's 
#one dimensional array

(6,)

In [6]:
#Get type
a.dtype

dtype('int32')

In [7]:
#Get size
a.size

6

In [8]:
#Get dimension
a.ndim

1

In [9]:
#Now here we'll define two dimensional array
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
#Get shape
b.shape
#Here in the output you'll get (Rows,Coloumns) as output i.e (2,3)

(2, 3)

In [11]:
#Get size
b.size

6

In [12]:
#Get dimension
b.ndim

2

In [15]:
#Get type
b.dtype

dtype('int32')

# Accessing/changing specific elements,rows,coloumns etc 

In [16]:
c=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [17]:
#Get a specific element  [r,c]
c[0,3]

4

In [18]:
#Get a specific row
c[0,:]

array([1, 2, 3, 4, 5])

In [19]:
#Get a specific coloumn
c[:,1]

array([2, 7])

In [21]:
#Get a specific number of elements in rows [row,start:stop:step]
c[0,1:5:2]

array([2, 4])

In [23]:
#Changing the numbers in the matrix
c[0,0]=2
print(c)

[[ 2  2  3  4  5]
 [ 6  7  8  9 10]]


In [25]:
#3 dimension example

# Initializing different types of Arrays

In [7]:
#creating zeros matrix
np.zeros((3,3)) #The matrix will be in the form of float

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
#creating ones matrix
y=np.ones((3,3),dtype='int64')
print(y)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [11]:
#Any other number
z=np.full((2,2),55)
print(z)

[[55 55]
 [55 55]]


In [12]:
#Random decimal numbers
np.random.rand(2,4)

array([[0.82865359, 0.70635823, 0.59898951, 0.35557593],
       [0.30647325, 0.29691524, 0.4535908 , 0.22469025]])

In [16]:
#Random sample method creates a matrix shape which you wish you should pass them as an arguments
np.random.random_sample(a.shape)

array([0.41620261, 0.62104948, 0.53556029, 0.31456492, 0.05458594,
       0.87126079])

In [18]:
#Random integer numbers
np.random.randint(2,7,size=(3,3))  #Here the matrix size is passed seperately consider this is important

array([[5, 3, 2],
       [6, 3, 2],
       [3, 6, 6]])

In [20]:
#Identity matrix
q=np.identity(3,dtype='int32')
print(q)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [23]:
#Repeating an array
arr=np.array([[1,2,3]])
rep=np.repeat(arr,4,axis=0)
print(rep)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]



# Copying numpy arrays

In [25]:
r=np.array([1,2,3])
s=r.copy()
print("Array R is:",r)
s[0]=100
print("Array S is:",s)

Array R is: [1 2 3]
Array S is: [100   2   3]


# Mathematics

In [40]:
t=np.array([1,2,3,4,5])
print(t)

[1 2 3 4 5]


In [41]:
#Addition
t+2

array([3, 4, 5, 6, 7])

All similar mathematical operations can be done using numpy

In [43]:
np.cos(t)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029,  0.75390225])

In [44]:
np.sin(t)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ])

# Linear Algebra

In [6]:
x=np.ones((2,3))
print(x)
y=np.full((3,2),3)
print(y)
#Use matmul function in numpy
z=np.matmul(x,y)
print(z)

[[1. 1. 1.]
 [1. 1. 1.]]
[[3 3]
 [3 3]
 [3 3]]
[[9. 9.]
 [9. 9.]]


In [9]:
#finding the determinant of any matrix
a=np.identity(3)
np.linalg.det(a)


1.0

# statistics

In [12]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [16]:
np.min(arr1)

1

In [17]:
np.max(arr1)

6

In [18]:
np.sum(arr1)

21

# Reorganizing Arrays

In [22]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
#vertical stacks
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v1,v2,v2])

In [26]:
#Horizontal stacks
h1=np.array([1,2,3])
h2=np.array([4,5,6])
np.hstack([h1,h2])

array([1, 2, 3, 4, 5, 6])